os: linux
dist: focal
language: python

python:
  - 3.8

install:
  - sudo apt -y install python3-distutils
  - sudo apt -y install python3-pip
  - sudo apt install -y git
  - git clone https://github.com/kivy/buildozer.git
  - python3 -m site
  - ls -l
  - cd buildozer
  - ls -l
  - python3 setup.py install
  - ls -l
  - cd ..
  - ls -l


  - sudo apt update
  - pip3 install --upgrade buildozer==1.2.0
  - pip3 list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1 | xargs -n1 pip3 install -U
  - pip3 install backports.entry-points-selectable==1.1.0
  - pip3 install distlib==0.3.2
  - pip3 install filelock==3.0.12
  - pip3 install platformdirs==2.2.0
  - pip3 install sh==1.14.2
  - pip3 install virtualenv==20.7.0
  - sudo apt install -y git zip unzip openjdk-8-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
  - pip3 install --upgrade Cython==0.29.19 virtualenv
  - export PATH=$PATH:~/.local/bin/
  - ls -l
  - echo "TODO COMPILE 32bit"
  - yes | buildozer android debug
  - ls -la
  - ls bin/ -l
  - gem install dpl --pre
  - dpl releases --token $GITHUB_TOKEN --file "bin/mobileapp001-0.3-armeabi-v7a-debug.apk" --tag_name "v.0.3"
  - echo "TODO COMPILE 64bit"
  - ls -l /home/travis/
  - ls -l /home/travis/build/WISEPLAT/mobile_app_001/
  - ls -la
  - rm -r -f .buildozer
  - ls -la
  - rm -r -f /home/travis/build/WISEPLAT/mobile_app_001/.buildozer
  - ls -l /home/travis/
  - ls -l /home/travis/build/WISEPLAT/mobile_app_001/
  - ls -l
  - yes | cp -f buildozer-64bit.spec buildozer.spec
  - yes | buildozer android debug
  - ls -la
  - ls bin/ -l
  - echo "TODO"
  - gem install dpl --pre
  - dpl releases --token $GITHUB_TOKEN --file "bin/mobileapp001-0.3-arm64-v8a-debug.apk" --tag_name "v.0.3"
  - echo "OK"
